SRCS = simpleloop.c matmul.c blocked.c linkedlist.c
PROGS = simpleloop matmul blocked linkedlist

all : $(PROGS)

$(PROGS) : % : %.c
	gcc -Wall -g -o $@ $<


traces: $(PROGS)
	./runit simpleloop
	./runit matmul 100
	./runit blocked 100 25
	./runit linkedlist 

.PHONY: clean

